# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/mercury4444/second:1.0 .
      - run: docker push ghcr.io/mercury4444/second:1.0
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run ghcr.io/mercury4444/second:1.0

  notify-build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.to }}
          token: ${{ secrets.token }}
          message: |
            build finished
            
  notify-deploy:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.to }}
          token: ${{ secrets.token }}
          message: |
            deploy finished
